---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demoapp-pv
spec:
  storageClassName: ""  
  capacity:
    storage: 8G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: demoapp-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demoapp-pv-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 6Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      name: demoapp-pod
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp-container
        image: learntechpuzz/demoapp
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html/"
            name: demoapp-pvc-storage   
            readOnly: true
      volumes:
        - name: demoapp-pvc-storage
          persistentVolumeClaim:
            claimName: demoapp-pv-claim  
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-svc-lb
spec:
  selector:
    app: demoapp
  type: LoadBalancer  
  ports:
    - port: 80
      targetPort: 80
---
      
